### ISSUE TITLE
大大，能否提交到 npm 库中，便于引用呢？

### ISSUE THREAD

**Issue by zhengmz** [androiddevelop/autosuggest.js#2]
谢谢

**Comment by androiddevelop** [comment]
已经提交， [hexo-search-data-plugin](https://www.npmjs.com/package/hexo-search-data-plugin)
使用示例参加工程example文件夹；

**Comment by zhengmz** [comment]
收到，谢谢

**Comment by zhengmz** [comment]
不过，改完之后不支持 ie8 了 ^o^

**Comment by androiddevelop** [comment]
> 

可以提供一个demo，我试试

**Comment by zhengmz** [comment]
我看了最新的源代码，之前定义变量的 var 改成了 let 或 const，这在 ie8 下无法识别，如

https://github.com/androiddevelop/autosuggest.js/blob/41e991a2ed82eb814cc44fb47618eb25a613b196/dist/autosuggest.js#L10

**Comment by androiddevelop** [comment]
晚些时候单独提供一个版本给你

**Comment by androiddevelop** [comment]
相关改动回滚了，可以试下1.1.2

**Comment by zhengmz** [comment]
太感谢
